@startuml core

set namespaceSeparator ::

namespace arcade {
    interface Core {
        
    }

    namespace lib {
        interface IGraphic {
            + init(scene)
            + update(scene, at)
            + end(scene)
        }
    }

    namespace ecs {
        interface IGame {
            + init(scene)
            + update(scene, at)
            + end(scene)
        }
    }

    interface Scene {
        
    }

    arcade::lib::IGraphic -up-* arcade::Core
    arcade::ecs::IGame -up-* arcade::Core
    arcade::Scene -up-* arcade::Core
}

@enduml