@startuml core

set namespaceSeparator ::

namespace arcade {
    class Core

    namespace lib {

        interface ILibrary {
            + init(scene)
            + update(scene, at)
            + end(scene)
        }

        interface IGraphic {
        }

        interface IGame {
        }

    }

    class Scene

    arcade::lib::ILibrary -up-* arcade::Core
    arcade::lib::IGraphic -up-|> arcade::lib::ILibrary
    arcade::lib::IGame -up-|> arcade::lib::ILibrary
    arcade::Scene -up-* arcade::Core

}

@enduml